server:
  port: 9090

spring:
  application:
    name: quickstart-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.10:31188
    sentinel:
      transport:
        dashboard: 192.168.3.10:31808
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
    org.springframework: info
